export type ProjectArtifact = {
  label: string
  path:  string
}

export type GalleryImage = {
  src:      string
  alt:      string
  caption?: string
}

export type ProjectGallery = {
  tokens?:     GalleryImage[]
  components?: GalleryImage[]
  kits?:       GalleryImage[]
}

export type RichSection =
  | { type: 'text';    label?: string; body: string }
  | { type: 'bullets'; label?: string; items: string[] }
  | { type: 'table';   label?: string; headers: string[]; rows: string[][] }

export type Project = {
  slug:         string
  type:         'CASE STUDY' | 'PORTFOLIO PROJECT'
  domainTag:    string
  name:         string
  org:          string
  year:         string
  brief:        string
  role:         string
  approach:     string[]
  deliverables: string[]
  takeaways:    string[]
  artifacts:    ProjectArtifact[]
  comingSoon:   boolean
  gallery?:     ProjectGallery
  richContent?: RichSection[]
  referenceArtifacts?: ProjectArtifact[]
}

export const PROJECTS: Project[] = [
  // ─── CASE STUDIES ───────────────────────────────────────────────────────────
  {
    slug:       'brintons-runner-carpet',
    type:       'CASE STUDY',
    domainTag:  'MANUFACTURING · QA',
    name:       'Brintons — Process Failure & Improvement',
    org:        'Brintons Carpets · India Design/Service Centre',
    year:       '2010 – 2013',
    brief:      'A critical process failure occurred when an incorrect carpet design was manufactured and supplied for a large-scale luxury hotel corridor project in the USA. The error — originating at the design stage — passed through every subsequent checkpoint undetected, resulting in the wrong product being delivered, urgent re-manufacturing, and significant reputational risk with a key hospitality client.',
    role:       'As Process Improvement Leader and PACE Champion for the Service Centre, I led the root cause analysis, identified process gaps, implemented corrective measures, and monitored their effectiveness.',
    approach: [
      'Conducted structured stakeholder interviews across Senior & Junior Designers, Project Managers, Planning, Production Design, and Design Support teams',
      'Built end-to-end business process maps to visualise the full workflow and identify key failure points',
      'Identified primary root cause: designer selected an incorrect pattern, colour, and dimension variant — not caught at any subsequent checkpoint',
      'Documented key failure points: no independent secondary validation before production approval; no QC checkpoint to match manufactured product against approved specification; no pre-shipment verification; communication gaps across Design, Production, and Logistics',
      'Developed detailed process flowcharts covering design validation, approval, and production QC',
      'Introduced mandatory two-level design validation and peer review before client approval submission',
      'Implemented formal digital approval process ensuring client sign-off before production',
      'Established QC checkpoints to verify manufactured carpets against approved designs',
      'Introduced pre-shipment verification and material traceability — linking each production batch to its approved specification',
      'Conducted cross-departmental training and introduced regular alignment meetings across Design, Production, and Logistics',
      'Implemented a Process Change Authorisation Procedure requiring documentation and sign-off for any deviation',
    ],
    deliverables: [
      'End-to-end business process maps covering design validation, approval, and production QC',
      'Process Change Authorisation Procedure — embedded as standard practice across the Service Centre',
      'SOPs for design validation, QC checkpoints, and pre-shipment verification',
      'Cross-functional training programme across Design, Production, and Logistics',
      'Corrective action tracking system for identified issues and implemented fixes',
      'Error rates reduced by over 50% following implementation of structured QC checkpoints and process controls',
      'Improved cross-functional alignment between Design, Production, and Logistics',
      'Strengthened quality governance framework reducing risk of recurrence on future high-value projects',
    ],
    takeaways: [
      'Process failures in complex supply chains often stem from small overlooked errors — preventative controls at multiple checkpoints are critical',
      'Structured RCA and stakeholder interviews surface the real root cause — not just the symptoms',
      'Cross-functional process mapping is essential for identifying where accountability and communication gaps exist',
      'Embedding quality controls and tracking mechanisms creates sustainable improvement — not just one-time fixes',
    ],
    artifacts: [
      { label: 'Case Study PDF', path: '/Projects/Case%20Studies/AK_CS_02_Brintons_Runner_Carpet.pdf' },
    ],
    comingSoon: false,
  },
  {
    slug:       'brintons-leave-encashment',
    type:       'CASE STUDY',
    domainTag:  'MANUFACTURING · COST',
    name:       'Brintons — Leave Encashment & Cost Optimisation',
    org:        'Brintons Carpets · India Design/Service Centre',
    year:       '2012',
    brief:      'January was consistently one of the costliest months at the Brintons India Service Centre due to accumulated leave encashment payouts. As PACE Champion, I led an initiative to encourage employees to avail balance leave rather than opt for encashment — reducing payout costs and enabling a single-shift model that generated additional savings across food, electricity, and transportation.',
    role:       'As PACE Champion for the Service Centre, I led the initiative from identification through to implementation and outcome tracking — coordinating across HR, Finance, Operations, and Planning.',
    approach: [
      'Engaged HR, Payroll, Finance, and Operations teams to understand the financial and operational impact of the existing leave encashment pattern',
      'Facilitated cross-functional discussions to define initiative scope, implementation approach, and communication plan',
      'Mapped the existing leave encashment process — identifying key trigger points driving January cost spikes',
      'Analysed operational impact of shifting from two-shift to single-shift model during the leave utilisation period',
      'Worked with Finance to validate projected savings across all cost heads',
      'Coordinated employee awareness sessions — communicating the initiative rationale and encouraging participation',
      'Developed SOPs for structured leave planning and encashment processes',
      'Established tracking mechanisms to monitor leave utilisation, shift patterns, and cost outcomes',
      'Conducted regular review meetings to address employee concerns and refine the approach',
    ],
    deliverables: [
      'SOPs for structured leave planning and encashment processes',
      'Cross-functional tracking mechanism covering leave utilisation, shift patterns, and cost outcomes',
      'Employee awareness sessions across the Service Centre',
      'Successful transition to single-shift operations during the leave utilisation period',
      'Cost savings in the range of £5K–£10K — recognised internally as a successful PACE outcome',
      'Savings achieved across food arrangements, electricity, and transportation',
      'Reduced sudden financial burden from bulk leave encashment payouts',
    ],
    takeaways: [
      'Small behavioural shifts — when properly analysed and communicated — can generate measurable financial impact',
      'Cross-functional stakeholder engagement is critical to successful policy implementation',
      'Tracking and quantifying outcomes builds credibility and supports a continuous improvement culture',
      'PACE-style initiatives demonstrate that process improvement extends beyond operations into HR and financial planning',
    ],
    artifacts: [
      { label: 'Case Study PDF', path: '/Projects/Case%20Studies/AK_CS_01_Brintons_Leave_Encashment.pdf' },
    ],
    comingSoon: false,
  },
  {
    slug:       'finance-analytics-dashboard',
    type:       'CASE STUDY',
    domainTag:  'BFSI · FINTECH',
    name:       'Finance Analytics & Dashboard',
    org:        'Opine Group · Deployed at Sarvatra Technologies Pvt. Ltd.',
    year:       '2017 – 2018',
    brief:      'Sarvatra Technologies, a BFSI/Fintech company providing Switch services to banks across India, relied on manual processes and fragmented Excel-based reporting to track revenue, expenses, transaction volumes, and settlement timelines. I was deployed as the sole on-site BA and BI resource to replace this with a centralised, automated analytics solution.',
    role:       'Sole on-site BA and BI resource — independently owning end-to-end delivery from initial requirements through to dashboard sign-off, with no on-site team support.',
    approach: [
      'Conducted requirement workshops with Finance, Accounts, and Senior Management to define dashboard objectives and reporting needs',
      'Identified key KPIs including revenue trends, settlement timelines, accounts receivable tracking, and financial reconciliation metrics',
      'Evaluated current reporting inefficiencies — including manual data consolidation, reconciliation inconsistencies, and lack of real-time visibility',
      'Performed gap analysis between existing processes and desired outcomes',
      'Created and maintained full project documentation — BRDs, functional specifications, ERDs, data dictionaries, and process workflows',
      'Designed the dimensional data model to support financial reporting — incorporating revenue, expenses, debtor tracking, and settlement timelines',
      'Integrated data from TallyERP and Excel sources into a unified dimensional data model',
      'Designed and implemented ETL packages (SSIS) and SQL queries for reliable, automated data flow',
      'Built a centralised finance dashboard and multiple SSRS analytics reports for Finance, Accounts, and Senior Management',
      'Designed test scenarios and validation criteria; conducted UAT with Finance users verifying dashboard outputs against TallyERP and Excel source records',
      'Managed feedback cycles, implemented refinements, and obtained formal stakeholder sign-off before deployment',
    ],
    deliverables: [
      'BRDs, functional specifications, ERDs, data dictionaries, and process workflows',
      'Dimensional data model integrating TallyERP and Excel sources',
      'ETL pipelines (SSIS) and SQL queries for automated data flow',
      'Centralised finance dashboard covering revenue, AR, dues, and settlement KPIs',
      'Multiple SSRS analytics reports for Finance, Accounts, and Senior Management',
      'UAT sign-off achieved with Finance and Senior Management stakeholders',
      'Report generation time reduced from hours to minutes',
      'Finance and Accounts teams gained real-time visibility into key financial metrics',
      'Foundation established for scalable, data-driven financial reporting across the organisation',
    ],
    takeaways: [
      'Aligning stakeholder expectations early — across Finance, Accounts, and Senior Management — ensures a clear, shared project direction',
      'Gap analysis is critical for identifying reporting inefficiencies before jumping to technical solutions',
      'Sole on-site delivery demands strong self-management, clear communication, and end-to-end ownership across both BA and BI tracks',
      'User involvement in UAT improves adoption and ensures the final solution genuinely addresses business needs',
      'Consolidating fragmented data sources into a single dimensional model is the foundation of reliable BI delivery',
    ],
    artifacts: [
      { label: 'Case Study PDF', path: '/Projects/Case%20Studies/AK_CS_03_Opine_Sarvatra.pdf' },
    ],
    comingSoon: false,
  },
  {
    slug:       'iddac',
    type:       'CASE STUDY',
    domainTag:  'GOVERNMENT · ANALYTICS',
    name:       'IDDAC — Govt. Analytics Platform',
    org:        'Savitribai Phule Pune University · Tribal Development Dept., Govt. of Maharashtra',
    year:       '2018 – 2021',
    brief:      'The Intelligent Dashboard & Data Analytics Centre (IDDAC) was a centrally-funded government analytics initiative under Article 275(1) of the Indian Constitution — mandated to unify fragmented data across 6 live welfare applications serving approximately 1 crore tribal beneficiaries across Maharashtra. I served as Sr. Project Consultant across BA, BI, and project management tracks.',
    role:       'Sr. Project Consultant at the Department of Technology, SPPU — with primary responsibility across both the BA and BI tracks, working alongside the Project Manager. Role evolved to include project management activities. Full BA+BI delivery for the Swayam & Hostel module; partial BI work across other TDD applications subject to project stage and resource availability.',
    approach: [
      'Engaged senior government stakeholders across TDD (Secretary level) and TRTI (Commissioner level), and coordinated with field offices spanning 4 Additional Tribal Commissioners and 29 Project Offices across Maharashtra',
      'Conducted stakeholder interviews, one-on-one and group meetings, and facilitated formal requirement workshops',
      'Mapped AS-IS workflows and data flows across 6 live TDD applications — identifying fragmentation points, data ownership gaps, and consolidation priorities',
      'Coordinated with multiple government IT vendors (Mahaonline, Probity Soft, NIC) to understand existing data structures and integration constraints',
      'Defined high-level functional and non-functional requirements for the analytics platform',
      'Contributed to data governance framework discussions covering data accuracy, integrity, and access controls',
      'For the Swayam & Hostel module: gathered end-to-end requirements covering hostel admissions, scholarship management, fund allocation, and student data flows',
      'Defined KPIs and reporting logic for fund allocation tracking, hostel occupancy, and student admissions data',
      'Developed dashboard specifications and data visualisation requirements for the Swayam module',
      'Navigated vendor delays through persistent follow-up, escalation, and clear requirement documentation',
      'Maintained detailed documentation across frequent government stakeholder changes to ensure continuity',
      'Managed budget reappropriation and utilization certificate submissions',
    ],
    deliverables: [
      'Full BA+BI delivery for the Swayam & Hostel module — successfully deployed for TDD staff',
      'AS-IS workflow and data flow mapping across 6 live TDD applications',
      'Requirements documentation, process maps, and data governance contributions',
      'KPI frameworks and dashboard specifications for the Swayam & Hostel module',
      'Training materials and user documentation for platform onboarding',
      'Stakeholder engagement across TDD (Secretary level), TRTI (Commissioner level), 4 ATCs, and 29 Project Offices',
      'Project governance — requirement tracking, budget reappropriation, and utilization certificate submissions',
      'Note: The broader IDDAC platform did not reach full deployment due to vendor, hardware, and stakeholder constraints. The Swayam module was the primary functional output of the engagement.',
    ],
    takeaways: [
      'Government-scale BA engagements require deep stakeholder management skills — navigating seniority, institutional complexity, and frequent personnel changes',
      'Mapping data flows across fragmented, multi-vendor government systems demands structured analytical thinking and persistent stakeholder coordination',
      'External constraints — vendor delays, trade restrictions, bureaucratic processes — are real delivery risks in large public sector initiatives. Documenting them professionally and maintaining delivery continuity is a core BA competency',
      'Delivering a working module under constraints demonstrates problem-solving and ownership beyond standard BA scope',
      'Operating across BA, BI, and PM tracks simultaneously builds a well-rounded delivery capability valuable in resource-constrained environments',
    ],
    artifacts: [
      { label: 'Case Study PDF', path: '/Projects/Case%20Studies/AK_CS_04_IDDAC.pdf' },
    ],
    comingSoon: false,
  },
  {
    slug:       'ak-brand-os',
    type:       'CASE STUDY',
    domainTag:  'DESIGN SYSTEMS · AI ENGINEERING',
    name:       'AK Brand OS — Design System',
    org:        'Independent · Built with Claude Design & Claude Code',
    year:       'Ongoing (V4)',
    brief:      'AK Brand OS is my personal design system — one token set and one component language applied across every artefact I produce, from BRDs and strategy memos to my resume, slide decks, dashboard, and this portfolio site. Built with Claude Design and Claude Code, it extracts a shared visual language from documents I already use in practice, rather than starting from a mood board.',
    role:       'I defined the brand premise and the five governing principles behind the system, sourced from my own Artefact Standards spec sheet, and supplied every source document the tokens were extracted from. Claude Design and Claude Code handled extraction, token generation, and the applied UI kits; I reviewed every token, component, and substitution against the original spec and directed scope — what shipped in V4, what stayed flagged open, and what comes next.',
    approach: [
      'Supplied real working documents — a BRD template, strategy memo, research report, presentation deck, and learning-notes system — as raw material, rather than designing tokens from a blank slate',
      'Used Claude Design to extract a shared token and component language from those documents, cross-checked against a pre-existing "Artefact Standards" spec sheet',
      'Defined five governing principles — Structured Diagnosis, Show Thinking, One Insight Per Block, Metadata Always Visible, Consistency in Elements — as the design intent behind every token decision',
      'Constrained the palette deliberately: one signal colour (orange), one serif (Fraunces), one sans (Geist), one mono (JetBrains Mono), a warm paper canvas, and a 4px spacing grid',
      'Packaged the system as a portable Claude Code Skill (SKILL.md), kept in sync via a custom /design-sync workflow — incremental updates, never a wholesale replace',
      'Generated an oxlint adherence config that blocks raw hex/px values and unauthorized fonts in downstream code, enforcing the tokens at the linting level',
      'Reviewed every extracted token, component, and substitution — including catching an IBM Plex Mono → Serif swap — against the original spec sheet before sign-off',
    ],
    deliverables: [
      'Full design token reference — colour, type, spacing, radii, shadows, and motion — documented in the system\'s design-tokens spec',
      'Six applied UI kits built on the same token set: resume, BRD/strategy-memo ("Universal Document"), dashboard, portfolio, social carousel, and slides',
      'A portable Claude Code Skill (SKILL.md) plus a /design-sync workflow for keeping downstream implementations incrementally aligned with the source system',
      'An auto-generated oxlint adherence config enforcing token usage in code',
      'This portfolio site itself runs on AK Brand OS as its applied production example',
      'V4 shipped as the current version, with open items logged rather than silently resolved',
    ],
    takeaways: [
      'A design system is more credible when extracted from real working documents than invented from a moodboard — it starts already proven in practice',
      'Narrow, disciplined constraints (one accent colour, three type families, one spacing unit) produce more consistency than an open palette ever would',
      'Flagging open issues explicitly — like this live site\'s theme not yet reconciled with the V4 paper-canvas spec, or the icon library being a best-guess substitution — is more useful than quietly shipping unresolved decisions',
      'Versioning discipline matters: informal labels ("V4" externally, "alpha" internally) create confusion a single consistent identifier would avoid',
      'Directing an AI collaborator still requires the human to own the spec, review every substitution, and decide scope — the system reflects editorial judgement, not automation alone',
    ],
    artifacts: [
      { label: 'Source Repo (GitHub)', path: 'https://github.com/Starquake82/ak-brand-os' },
      { label: 'Notion Doc', path: 'https://app.notion.com/p/3910adb7af6081a68ddaf75b23621619' },
    ],
    comingSoon: false,
    gallery: {
      tokens: [
        { src: '/Projects/ak-brand-os/tokens/colors-paper.png', alt: 'Paper canvas colour palette', caption: 'Paper Canvas' },
        { src: '/Projects/ak-brand-os/tokens/colors-signal.png', alt: 'Signal orange colour palette', caption: 'Signal Colour' },
        { src: '/Projects/ak-brand-os/tokens/type-families.png', alt: 'Type family specimens — Fraunces, Geist, JetBrains Mono', caption: 'Type Families' },
        { src: '/Projects/ak-brand-os/tokens/spacing-scale.png', alt: '4px-based spacing scale', caption: 'Spacing Scale' },
      ],
      components: [
        { src: '/Projects/ak-brand-os/components/01-logo-lockups.png', alt: 'AK logo lockup variants', caption: 'Logo Lockups' },
        { src: '/Projects/ak-brand-os/components/11-colors-ink.png', alt: 'Ink colour tokens in context', caption: 'Ink Colours' },
        { src: '/Projects/ak-brand-os/components/20-type-serif-display.png', alt: 'Fraunces serif display type in use', caption: 'Serif Display' },
        { src: '/Projects/ak-brand-os/components/40-buttons.png', alt: 'Button component variants', caption: 'Buttons' },
        { src: '/Projects/ak-brand-os/components/44-stats.png', alt: 'Stat component variants', caption: 'Stats' },
        { src: '/Projects/ak-brand-os/components/45-bar-chart.png', alt: 'Bar chart component', caption: 'Bar Chart' },
        { src: '/Projects/ak-brand-os/components/46-process-ribbon.png', alt: 'Process ribbon component', caption: 'Process Ribbon' },
        { src: '/Projects/ak-brand-os/components/50-table-document.png', alt: 'Document table component', caption: 'Document Table' },
      ],
      kits: [
        { src: '/Projects/ak-brand-os/kits/resume-ui-kit.png', alt: 'Resume UI kit applying the design system', caption: 'Resume' },
        { src: '/Projects/ak-brand-os/kits/brd-ui-kit.png', alt: 'BRD / strategy memo UI kit', caption: 'BRD / Document' },
        { src: '/Projects/ak-brand-os/kits/kit-dashboard.png', alt: 'Dashboard UI kit', caption: 'Dashboard' },
        { src: '/Projects/ak-brand-os/kits/kit-portfolio.png', alt: 'Portfolio site UI kit', caption: 'Portfolio Site' },
        { src: '/Projects/ak-brand-os/kits/kit-social.png', alt: 'Social carousel UI kit', caption: 'Social Carousel' },
        { src: '/Projects/ak-brand-os/kits/kit-slides.png', alt: 'Slides / presentation UI kit', caption: 'Slides Deck' },
      ],
    },
  },
  // ─── PORTFOLIO PROJECTS (comingSoon) ────────────────────────────────────────
  {
    slug:       'library-management-portal',
    type:       'PORTFOLIO PROJECT',
    domainTag:  'LIBRARY SYSTEMS',
    name:       'Library Management Portal',
    org:        'BACentric Capstone Project',
    year:       'Independent',
    brief:      'An independent BA capstone project for BACentric certification — full requirements-to-wireframe delivery for an Online Library Management System, covering member management, catalogue search, book issuance and returns, and fine tracking.',
    role:       'Sole Business Analyst for this independent capstone project — owned requirements gathering, process mapping, and solution design end-to-end, from initial project brief through to wireframes and validation criteria.',
    approach: [
      'Authored a Project Brief defining the problem statement, objectives, and scope for an Online Library Management System',
      'Mapped As-Is and To-Be business processes to identify manual bottlenecks in book issuance, returns, and member management',
      'Produced a combined As-Is & To-Be process flow document to visualise the transition from manual to system-based operations',
      'Authored a Business Requirements Document (BRD) covering functional and non-functional requirements',
      'Broke down requirements into Epics and User Stories for a phased delivery approach',
      'Designed wireframes covering core library workflows — member registration, catalogue search, book issue/return, and fine management',
      'Built a Validation Sheet defining test scenarios and acceptance criteria against the documented requirements',
    ],
    deliverables: [
      'Project Brief — problem statement, objectives, and scope definition',
      'As-Is & To-Be Process Flow documentation',
      'Business Requirements Document (BRD)',
      'Epics & User Stories backlog',
      'UI Wireframes covering core library management workflows',
      'Validation Sheet — test scenarios and acceptance criteria',
    ],
    takeaways: [
      'Mapping As-Is process pain points before defining To-Be workflows kept requirements grounded in real operational friction rather than assumed functionality',
      'Breaking the BRD into Epics and User Stories made scope easier to sequence and validate incrementally',
      'Building the validation sheet alongside the requirements — not after — surfaced ambiguous acceptance criteria early',
    ],
    artifacts: [
      { label: 'Project Brief',         path: '/Projects/library-portal/BAC%20-%20Project%20Brief%20%E2%80%93%20Online%20Library%20Management%20System.docx' },
      { label: 'BRD',                   path: '/Projects/library-portal/BAC%20-%20Library%20Management%20Portal-BRD.docx' },
      { label: 'Epics & User Stories',  path: '/Projects/library-portal/BAC%20-%20Library%20Management%20Portal-Epics%20&%20User%20Stories.docx' },
      { label: 'As-Is & To-Be Process', path: '/Projects/library-portal/BAC%20-%20Library%20Management%20As-Is%20&%20To-Be%20Process.pdf' },
      { label: 'Wireframes PDF',        path: '/Projects/library-portal/BAC%20-%20Library%20Management%20Portal-Wireframes.pdf' },
      { label: 'Validation Sheet',      path: '/Projects/library-portal/BAC%20-%20Library%20Management%20Portal%20-%20Validation%20Sheet.xlsx' },
    ],
    comingSoon: false,
    gallery: {
      components: [
        { src: '/Projects/library-portal/BAC%20-%20Project%20Brief%20%E2%80%93%20Screenshot.png', alt: 'Library Management project brief screenshot', caption: 'Project Brief' },
        { src: '/Projects/library-portal/BAC%20-%20Library%20Management%20As-Is.drawio.png', alt: 'Library Management As-Is process diagram', caption: 'As-Is Process' },
        { src: '/Projects/library-portal/BAC%20-%20Library%20ManagementTo-Be.drawio.png', alt: 'Library Management To-Be process diagram', caption: 'To-Be Process' },
      ],
    },
  },
  {
    slug:       'procurement-management-portal',
    type:       'PORTFOLIO PROJECT',
    domainTag:  'PROCUREMENT OPS',
    name:       'Procurement Management Portal',
    org:        'BACentric Capstone Project',
    year:       'Independent',
    brief:      'An independent BA capstone project for BACentric certification — full requirements-to-wireframe delivery for a Procurement Management Portal, covering requisitions, approvals, purchase orders, RFQs, goods receipt, and payment tracking across employee, warehouse, and vendor-facing workflows.',
    role:       'Sole Business Analyst for this independent capstone project — owned end-to-end requirements definition, process mapping, use case design, and wireframing for a full procure-to-pay portal.',
    approach: [
      'Authored a Project Brief and As-Is process flow mapping the existing manual procurement process at ABC Tech, the case-study organisation',
      'Mapped To-Be process flow spanning requisition, approval, purchase order, goods receipt, and payment stages',
      'Authored a Business Requirements Document (BRD) covering employee, warehouse, approval, and vendor-facing workflows',
      'Broke down requirements into Epics and User Stories for phased delivery',
      'Modelled system interactions with a UML Use Case diagram covering all user roles',
      'Documented representative Use Case examples and a working Requirements draft to validate scope',
      'Designed a full wireframe set (34 screens) covering authentication, employee and warehouse dashboards, purchase orders, RFQs, goods receipt notes, and payment status tracking',
      'Built a Validation Sheet defining test scenarios and acceptance criteria against the documented requirements',
      'Referenced sample purchase orders, a GRN, and an RFQ template to ground requirements in realistic document formats',
    ],
    deliverables: [
      'Project Brief and As-Is / To-Be Process Flow documentation',
      'Business Requirements Document (BRD)',
      'Epics & User Stories backlog',
      'UML Use Case diagram',
      'Use Case examples and Requirements draft',
      'UI Wireframes — 34 screens covering the full procure-to-pay workflow, login through payment status',
      'Validation Sheet — test scenarios and acceptance criteria',
    ],
    takeaways: [
      'A multi-role system (employee, warehouse, approver, vendor) required use case modelling to keep permissions and workflow branches unambiguous before wireframing',
      'Designing 34 screens end-to-end surfaced edge cases — password reset flows, multi-variant PO views — that a single-happy-path wireframe set would have missed',
      'Keeping the Validation Sheet aligned to the BRD line-by-line made later scope discussions traceable back to a specific requirement',
    ],
    artifacts: [
      { label: 'Project Brief',         path: '/Projects/procurement-portal/Project%20Brief%20%E2%80%93%20Procurement%20Management%20Portal%20(PMP).docx' },
      { label: 'BRD',                   path: '/Projects/procurement-portal/BRD%20-%20Procurement%20Management%20Portal%20(PMP).docx' },
      { label: 'Epics & User Stories',  path: '/Projects/procurement-portal/Epics%20&%20User%20Stories%20-%20Procurement%20Management%20Portal%20(PMP).docx' },
      { label: 'Use Cases (Examples)',  path: '/Projects/procurement-portal/Procurement%20Management%20Portal%20(PMP)-Use%20Cases%20(Examples).xlsx' },
      { label: 'Requirements Draft',    path: '/Projects/procurement-portal/Requirements%20draft.xlsx' },
      { label: 'As-Is & To-Be Process', path: '/Projects/procurement-portal/Procurement%20Management%20Portal%20(PMP)%20-%20As-Is%20&%20To-Be%20Process%20Flow.pdf' },
      { label: 'Wireframes PDF (All)',  path: '/Projects/procurement-portal/PMP%20Wireframes%20-%20All.pdf' },
      { label: 'Validation Sheet',      path: '/Projects/procurement-portal/Procurement%20Management%20Portal%20(PMP)-%20Validation%20Sheet.xlsx' },
    ],
    comingSoon: false,
    gallery: {
      components: [
        { src: '/Projects/procurement-portal/Project%20Brief%20-%20Procurement%20Management%20Portal%20(PMP)%20-%20Process%20flow.jpg', alt: 'Procurement Management Portal project brief process flow', caption: 'Project Brief — Process Flow' },
        { src: '/Projects/procurement-portal/As-Is%20Process%20Flow%20for%20ABC%20Tech%20Procuremet%20Process.png', alt: 'ABC Tech As-Is procurement process flow', caption: 'As-Is Process' },
        { src: '/Projects/procurement-portal/To-Be%20Process%20Flow%20-%20Procurement%20Management%20Portal%20(PMP).drawio.png', alt: 'Procurement Management Portal To-Be process flow', caption: 'To-Be Process' },
        { src: '/Projects/procurement-portal/Procurement%20Management%20Portal%20(PMP)-UML%20Use%20Case%20Diagram.jpg', alt: 'Procurement Management Portal UML use case diagram', caption: 'UML Use Case Diagram' },
      ],
      kits: [
        { src: '/Projects/procurement-portal/wireframes/PMP%20Login%20Screen.png', alt: 'PMP Login screen wireframe', caption: 'Login' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Register.png', alt: 'PMP Register screen wireframe', caption: 'Register' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Reset%20Password%20Request.png', alt: 'PMP password reset request wireframe', caption: 'Reset Password — Request' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Reset%20Password%20Request%20Submited.png', alt: 'PMP password reset request submitted wireframe', caption: 'Reset Password — Submitted' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Reset%20Password%20New%20Password.png', alt: 'PMP set new password wireframe', caption: 'Reset Password — New Password' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Reset%20Password%20Complete.png', alt: 'PMP password reset complete wireframe', caption: 'Reset Password — Complete' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Employee%20Dash.png', alt: 'PMP Employee dashboard wireframe', caption: 'Employee Dashboard' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Approval%20-%20Lead%20Management%20Dash.png', alt: 'PMP Approval / Lead Management dashboard wireframe', caption: 'Approval / Lead Management Dashboard' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Approval%20-%20Lead%20Management%20Dash%20updated%201.png', alt: 'PMP Approval / Lead Management dashboard wireframe, updated', caption: 'Approval / Lead Management Dashboard (Updated)' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Warehouse%20Dash.png', alt: 'PMP Warehouse dashboard wireframe', caption: 'Warehouse Dashboard' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Warehouse%20Dash%20New%201.png', alt: 'PMP Warehouse dashboard wireframe, variant 1', caption: 'Warehouse Dashboard (New 1)' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Warehouse%20Dash%20New%202.png', alt: 'PMP Warehouse dashboard wireframe, variant 2', caption: 'Warehouse Dashboard (New 2)' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20PO%20Create.png', alt: 'PMP Purchase Order creation wireframe', caption: 'PO — Create' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20PO%20View.png', alt: 'PMP Purchase Order view wireframe', caption: 'PO — View' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20PO%20View%20updated1.png', alt: 'PMP Purchase Order view wireframe, updated variant 1', caption: 'PO — View (Updated 1)' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20PO%20View_updated1.png', alt: 'PMP Purchase Order view wireframe, updated variant 1b', caption: 'PO — View (Updated 1b)' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20PO%20View_updated2.png', alt: 'PMP Purchase Order view wireframe, updated variant 2', caption: 'PO — View (Updated 2)' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20GRN.png', alt: 'PMP Goods Receipt Note wireframe', caption: 'Goods Receipt Note (GRN)' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Hardware%20Request%20Form.png', alt: 'PMP Hardware Request Form wireframe', caption: 'Hardware Request Form' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20RFQ%20New.jpg', alt: 'PMP new RFQ wireframe', caption: 'RFQ — New' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20RFQ%20View.png', alt: 'PMP RFQ view wireframe', caption: 'RFQ — View' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20RFQ%20-%20Compare%20Quotes.png', alt: 'PMP RFQ compare quotes wireframe', caption: 'RFQ — Compare Quotes' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20RFQs%20View.png', alt: 'PMP RFQs list view wireframe', caption: 'RFQs — View All' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Quote%20Submission%20Form.png', alt: 'PMP Quote submission form wireframe', caption: 'Quote Submission Form' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Payment%20Status%20View.png', alt: 'PMP Payment status view wireframe', caption: 'Payment Status — View' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Payment%20Status%20update.png', alt: 'PMP Payment status update wireframe', caption: 'Payment Status — Update' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Accounts%203-Way%20Matching1%20.png', alt: 'PMP Accounts 3-way matching wireframe, step 1', caption: '3-Way Matching — Step 1' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Accounts%203-Way%20Matching2.png', alt: 'PMP Accounts 3-way matching wireframe, step 2', caption: '3-Way Matching — Step 2' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Accounts%203-Way%20Matching3.png', alt: 'PMP Accounts 3-way matching wireframe, step 3', caption: '3-Way Matching — Step 3' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Accounts%203-Way%20Matching4.png', alt: 'PMP Accounts 3-way matching wireframe, step 4', caption: '3-Way Matching — Step 4' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Accounts%203-Way%20Matching5.png', alt: 'PMP Accounts 3-way matching wireframe, step 5', caption: '3-Way Matching — Step 5' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Notifications.png', alt: 'PMP Notifications screen wireframe', caption: 'Notifications' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Logout%201.png', alt: 'PMP Logout wireframe, variant 1', caption: 'Logout (1)' },
        { src: '/Projects/procurement-portal/wireframes/PMP%20Logout%202.png', alt: 'PMP Logout wireframe, variant 2', caption: 'Logout (2)' },
      ],
    },
    referenceArtifacts: [
      { label: 'GRN Sample (ClearTax)',         path: '/Projects/procurement-portal/reference/GRN_sample_cleartax.in.jpeg' },
      { label: 'PO Sample',                     path: '/Projects/procurement-portal/reference/PO%20sample.png' },
      { label: 'PO Sample — Variant 2',         path: '/Projects/procurement-portal/reference/PO.png' },
      { label: 'PO Sample — Variant 3',         path: '/Projects/procurement-portal/reference/PO2.png' },
      { label: 'PO Sample — Variant 4',         path: '/Projects/procurement-portal/reference/PO3.png' },
      { label: 'RFQ Template',                  path: '/Projects/procurement-portal/reference/Request%20For%20Quotation.pdf' },
      { label: 'RFQ Evaluation Template',       path: '/Projects/procurement-portal/reference/rfq-evaluation-template.pdf' },
      { label: 'Integration Touchpoints Guide', path: '/Projects/procurement-portal/reference/Integration%20Touchpoints%20Guide.pdf' },
    ],
  },
  {
    slug:         'maven-aw-dashboard',
    type:         'PORTFOLIO PROJECT',
    domainTag:    'SALES & RETAIL ANALYTICS',
    name:         'Maven AW Power BI Dashboard',
    org:          'Maven Analytics',
    year:         'Independent',
    brief:        '',
    role:         '',
    approach:     [],
    deliverables: [],
    takeaways:    [],
    artifacts:    [],
    comingSoon:   true,
  },
  {
    slug:         'finbridge-los',
    type:         'PORTFOLIO PROJECT',
    domainTag:    'BFSI · LENDING',
    name:         'FinBridge LOS',
    org:          'Independent Portfolio Project',
    year:         'In Progress',
    brief:        '',
    role:         '',
    approach:     [],
    deliverables: [],
    takeaways:    [],
    artifacts:    [],
    comingSoon:   true,
  },
  // ─── AI-ASSISTED BUILD ──────────────────────────────────────────────────────
  {
    slug:       'abhishekak-site',
    type:       'CASE STUDY',
    domainTag:  'AI · WEB DELIVERY',
    name:       'abhishekak.site — AI-Assisted Portfolio Build',
    org:        'Independent · Built with Claude Code',
    year:       '2026',
    comingSoon: false,

    brief: 'Professional BA and BI experience is difficult to convey through a CV alone — work quality, analytical structure, and delivery approach are invisible without evidence. This portfolio addresses that gap: 15 years of structured analysis work translated into a navigable, evidence-led digital product, combining case studies, project artefacts, CVs, certifications, and process documentation in a single accessible reference. Built and delivered by an analyst with zero coding background using a structured AI-assisted workflow. The project follows one principle: Structured Diagnosis for Business, Systems & AI.',

    role:        '—',
    approach:    [],
    deliverables:[],
    takeaways:   [],

    richContent: [
      {
        type:  'bullets',
        label: '02 / WHY THIS PROJECT EXISTS',
        items: [
          'BO-01 — Evidence-Led Portfolio: Present BA, BI, and process improvement experience through structured case studies, documented artefacts, and navigable sections — not through claims alone',
          'BO-02 — AI Delivery Demonstration: Demonstrate that an analyst with no prior web development background can specify, direct, review, and deliver a production-quality web product using an AI-assisted coding workflow',
          'BO-03 — Analyst-as-Product-Owner: Show how a business analyst can act simultaneously as product owner, content architect, reviewer, and delivery lead — with AI as the implementation partner',
        ],
      },
      {
        type:  'bullets',
        label: '03 / AI IMPLEMENTATION ROLE',
        items: [
          'Translated structured requirements into React / Next.js components',
          'Built and iterated layout, animation, routing, and interaction behaviour',
          'Structured portfolio content into typed data models',
          'Accelerated delivery from concept to deployed site',
        ],
      },
      {
        type:  'bullets',
        label: 'HUMAN PRODUCT OWNER ROLE — ABHISHEK KININGE',
        items: [
          'Defined business objectives and product scope',
          'Supplied domain knowledge, professional context, and case-study content',
          'Reviewed all outputs for accuracy, tone, and business relevance',
          'Validated portfolio evidence and directed final user experience',
          'Authored all session briefs and acceptance criteria',
        ],
      },
      {
        type:    'table',
        label:   '04 / BA & BI SKILLS DEMONSTRATED',
        headers: ['Domain', 'Skills'],
        rows: [
          ['Business Analysis',    'Requirements elicitation, process mapping, BRD writing, user stories, stakeholder management, gap analysis'],
          ['Business Intelligence','Power BI (Desktop + Service + DAX), data modelling, dashboard design, KPI definition'],
          ['Process Improvement',  'Root cause analysis, waste identification, process reengineering, cost optimisation'],
          ['Documentation',        'Wireframes, use case documentation, validation sheets, process flow diagrams'],
          ['Domain Knowledge',     'BFSI · Manufacturing · Retail Analytics · Government · Healthcare · Library Systems'],
        ],
      },
      {
        type:    'table',
        label:   '05 / AI & TECHNICAL SKILLS DEMONSTRATED',
        headers: ['Domain', 'Skills'],
        rows: [
          ['AI-Assisted Delivery', 'Claude Code prompt engineering, session brief authoring, AI output review and direction'],
          ['Frontend',             'React 19, Next.js 16 App Router, TypeScript, Tailwind CSS v4'],
          ['Animation',            'GSAP + ScrollTrigger (horizontal pin scroll, scroll-triggered entrance), Lenis smooth scroll'],
          ['Routing',              'App Router dynamic routes, static params generation, async server components'],
          ['Data Modelling',       'Typed project data structures in TypeScript (projectData.ts)'],
        ],
      },
      {
        type:  'bullets',
        label: '06 / PRODUCT FEATURES',
        items: [
          'Hero — Canvas particle mesh, animated headline with rotating text, entrance animation',
          'Work / Experience — GSAP vertical snap timeline, company logo grid (35+ logos)',
          'Projects & Case Studies — Horizontal pinned scroll track, 10 cards (4 portfolio projects + 6 case studies), individual project detail pages with PDF artefact viewer',
          'Certifications — Dual horizontal marquee of certificate cards',
          'About — Count-up stats, personal context section',
          'Contact — Styled contact form with social links',
          'Admin Route — /admin pipeline dashboard UI (Phase 2 placeholder; Run buttons disabled)',
          'PDF Artefact Viewer — Inline PDF popup with download option, image viewer with zoom',
          'Custom Cursor — Dot cursor with hover expand behaviour',
        ],
      },
      {
        type:    'table',
        label:   '07 / DELIVERABLES REGISTER',
        headers: ['Artefact Type', 'Contents', 'Location'],
        rows: [
          ['CV Documents',                   'BA-focused CV, BI-focused CV, Cover Letter',                         'public/CV/'],
          ['Case Study PDFs',                '6 BA/BI/Process case studies',                                      'public/Projects/Case Studies/'],
          ['BA Portfolio — Library Portal',  'Wireframes, BRD, process flows, user stories, validation sheet',    'public/Projects/library-portal/'],
          ['BA Portfolio — Procurement Portal','Wireframes, BRD, use cases, validation sheet, process flows',     'public/Projects/procurement-portal/'],
          ['BI Portfolio — Maven AW Dashboard','Power BI project files',                                          'public/Projects/maven-aw/'],
          ['BI Portfolio — FinBridge LOS',   'BFSI lending project documentation',                               'public/Projects/finbridge-los/'],
          ['Certificates',                   '12+ professional certificates (PDF and image)',                     'public/Certificates/'],
          ['Certification Badges',           'Digital badges from Maven Analytics, McKinsey, Google, IBM',        'public/Badges/'],
          ['Organisation Logos',             '35+ logos used in Experience and Education sections',               'public/Logos/'],
        ],
      },
      {
        type:    'table',
        label:   '08 / TECHNOLOGY STACK',
        headers: ['Category', 'Technology', 'Version'],
        rows: [
          ['Framework',    'Next.js',           '16.2.9'],
          ['Language',     'TypeScript',         '^5'],
          ['UI Library',   'React',              '19.2.4'],
          ['Styling',      'Tailwind CSS',        '^4'],
          ['Animation',    'GSAP + ScrollTrigger','^ 3.15'],
          ['Smooth Scroll','Lenis',               '^1.3'],
          ['Utilities',    'clsx',                '^2.1'],
          ['Utilities',    'tailwind-merge',      '^3.6'],
          ['Deployment',   'Vercel',              '—'],
        ],
      },
      {
        type:    'table',
        label:   '09 / DESIGN DIRECTION',
        headers: ['Token', 'Value', 'Usage'],
        rows: [
          ['--bg',     '#0A0A0A',                   'Page background'],
          ['--surface','#111111',                   'Cards, panels'],
          ['--text',   '#F2F0EB',                   'Primary text'],
          ['--muted',  'rgba(242,240,235,0.45)',     'Secondary text'],
          ['--accent', '#FF5A00',                   'Orange highlight, CTAs'],
          ['--border', 'rgba(255,255,255,0.07)',     'Dividers, card borders'],
        ],
      },
      {
        type:  'bullets',
        label: 'TYPOGRAPHY',
        items: [
          'Fraunces — Display headings (serif, optical)',
          'Geist — Body and UI text (sans-serif)',
          'JetBrains Mono — Section labels, tags, monospaced UI',
        ],
      },
    ],

    artifacts: [
      { label: 'Live Site',           path: 'https://abhishekak.site' },
      { label: 'GitHub Repo',         path: 'https://github.com/Starquake82/abhishekak-site' },
      { label: 'Notion Project Page', path: 'https://app.notion.com/p/3910adb7af6081f69cc6cea17771a60a' },
    ],
  },
]
