export type ProjectArtifact = {
  label: string
  path:  string
}

export type Project = {
  slug:         string
  type:         'CASE STUDY' | 'PORTFOLIO PROJECT'
  domainTag:    string
  name:         string
  org:          string
  year:         string
  brief:        string
  role:         string
  approach:     string[]
  deliverables: string[]
  takeaways:    string[]
  artifacts:    ProjectArtifact[]
  comingSoon:   boolean
}

export const PROJECTS: Project[] = [
  // ─── CASE STUDIES ───────────────────────────────────────────────────────────
  {
    slug:       'brintons-runner-carpet',
    type:       'CASE STUDY',
    domainTag:  'MANUFACTURING · QA',
    name:       'Brintons — Process Failure & Improvement',
    org:        'Brintons Carpets · India Design/Service Centre',
    year:       '2010 – 2013',
    brief:      'A critical process failure occurred when an incorrect carpet design was manufactured and supplied for a large-scale luxury hotel corridor project in the USA. The error — originating at the design stage — passed through every subsequent checkpoint undetected, resulting in the wrong product being delivered, urgent re-manufacturing, and significant reputational risk with a key hospitality client.',
    role:       'As Process Improvement Leader and PACE Champion for the Service Centre, I led the root cause analysis, identified process gaps, implemented corrective measures, and monitored their effectiveness.',
    approach: [
      'Conducted structured stakeholder interviews across Senior & Junior Designers, Project Managers, Planning, Production Design, and Design Support teams',
      'Built end-to-end business process maps to visualise the full workflow and identify key failure points',
      'Identified primary root cause: designer selected an incorrect pattern, colour, and dimension variant — not caught at any subsequent checkpoint',
      'Documented key failure points: no independent secondary validation before production approval; no QC checkpoint to match manufactured product against approved specification; no pre-shipment verification; communication gaps across Design, Production, and Logistics',
      'Developed detailed process flowcharts covering design validation, approval, and production QC',
      'Introduced mandatory two-level design validation and peer review before client approval submission',
      'Implemented formal digital approval process ensuring client sign-off before production',
      'Established QC checkpoints to verify manufactured carpets against approved designs',
      'Introduced pre-shipment verification and material traceability — linking each production batch to its approved specification',
      'Conducted cross-departmental training and introduced regular alignment meetings across Design, Production, and Logistics',
      'Implemented a Process Change Authorisation Procedure requiring documentation and sign-off for any deviation',
    ],
    deliverables: [
      'End-to-end business process maps covering design validation, approval, and production QC',
      'Process Change Authorisation Procedure — embedded as standard practice across the Service Centre',
      'SOPs for design validation, QC checkpoints, and pre-shipment verification',
      'Cross-functional training programme across Design, Production, and Logistics',
      'Corrective action tracking system for identified issues and implemented fixes',
      'Error rates reduced by over 50% following implementation of structured QC checkpoints and process controls',
      'Improved cross-functional alignment between Design, Production, and Logistics',
      'Strengthened quality governance framework reducing risk of recurrence on future high-value projects',
    ],
    takeaways: [
      'Process failures in complex supply chains often stem from small overlooked errors — preventative controls at multiple checkpoints are critical',
      'Structured RCA and stakeholder interviews surface the real root cause — not just the symptoms',
      'Cross-functional process mapping is essential for identifying where accountability and communication gaps exist',
      'Embedding quality controls and tracking mechanisms creates sustainable improvement — not just one-time fixes',
    ],
    artifacts: [
      { label: 'Case Study PDF', path: '/Projects/Case%20Studies/AK_CS_02_Brintons_Runner_Carpet.pdf' },
    ],
    comingSoon: false,
  },
  {
    slug:       'brintons-leave-encashment',
    type:       'CASE STUDY',
    domainTag:  'MANUFACTURING · COST',
    name:       'Brintons — Leave Encashment & Cost Optimisation',
    org:        'Brintons Carpets · India Design/Service Centre',
    year:       '2012',
    brief:      'January was consistently one of the costliest months at the Brintons India Service Centre due to accumulated leave encashment payouts. As PACE Champion, I led an initiative to encourage employees to avail balance leave rather than opt for encashment — reducing payout costs and enabling a single-shift model that generated additional savings across food, electricity, and transportation.',
    role:       'As PACE Champion for the Service Centre, I led the initiative from identification through to implementation and outcome tracking — coordinating across HR, Finance, Operations, and Planning.',
    approach: [
      'Engaged HR, Payroll, Finance, and Operations teams to understand the financial and operational impact of the existing leave encashment pattern',
      'Facilitated cross-functional discussions to define initiative scope, implementation approach, and communication plan',
      'Mapped the existing leave encashment process — identifying key trigger points driving January cost spikes',
      'Analysed operational impact of shifting from two-shift to single-shift model during the leave utilisation period',
      'Worked with Finance to validate projected savings across all cost heads',
      'Coordinated employee awareness sessions — communicating the initiative rationale and encouraging participation',
      'Developed SOPs for structured leave planning and encashment processes',
      'Established tracking mechanisms to monitor leave utilisation, shift patterns, and cost outcomes',
      'Conducted regular review meetings to address employee concerns and refine the approach',
    ],
    deliverables: [
      'SOPs for structured leave planning and encashment processes',
      'Cross-functional tracking mechanism covering leave utilisation, shift patterns, and cost outcomes',
      'Employee awareness sessions across the Service Centre',
      'Successful transition to single-shift operations during the leave utilisation period',
      'Cost savings in the range of £5K–£10K — recognised internally as a successful PACE outcome',
      'Savings achieved across food arrangements, electricity, and transportation',
      'Reduced sudden financial burden from bulk leave encashment payouts',
    ],
    takeaways: [
      'Small behavioural shifts — when properly analysed and communicated — can generate measurable financial impact',
      'Cross-functional stakeholder engagement is critical to successful policy implementation',
      'Tracking and quantifying outcomes builds credibility and supports a continuous improvement culture',
      'PACE-style initiatives demonstrate that process improvement extends beyond operations into HR and financial planning',
    ],
    artifacts: [
      { label: 'Case Study PDF', path: '/Projects/Case%20Studies/AK_CS_01_Brintons_Leave_Encashment.pdf' },
    ],
    comingSoon: false,
  },
  {
    slug:       'finance-analytics-dashboard',
    type:       'CASE STUDY',
    domainTag:  'BFSI · FINTECH',
    name:       'Finance Analytics & Dashboard',
    org:        'Opine Group · Deployed at Sarvatra Technologies Pvt. Ltd.',
    year:       '2017 – 2018',
    brief:      'Sarvatra Technologies, a BFSI/Fintech company providing Switch services to banks across India, relied on manual processes and fragmented Excel-based reporting to track revenue, expenses, transaction volumes, and settlement timelines. I was deployed as the sole on-site BA and BI resource to replace this with a centralised, automated analytics solution.',
    role:       'Sole on-site BA and BI resource — independently owning end-to-end delivery from initial requirements through to dashboard sign-off, with no on-site team support.',
    approach: [
      'Conducted requirement workshops with Finance, Accounts, and Senior Management to define dashboard objectives and reporting needs',
      'Identified key KPIs including revenue trends, settlement timelines, accounts receivable tracking, and financial reconciliation metrics',
      'Evaluated current reporting inefficiencies — including manual data consolidation, reconciliation inconsistencies, and lack of real-time visibility',
      'Performed gap analysis between existing processes and desired outcomes',
      'Created and maintained full project documentation — BRDs, functional specifications, ERDs, data dictionaries, and process workflows',
      'Designed the dimensional data model to support financial reporting — incorporating revenue, expenses, debtor tracking, and settlement timelines',
      'Integrated data from TallyERP and Excel sources into a unified dimensional data model',
      'Designed and implemented ETL packages (SSIS) and SQL queries for reliable, automated data flow',
      'Built a centralised finance dashboard and multiple SSRS analytics reports for Finance, Accounts, and Senior Management',
      'Designed test scenarios and validation criteria; conducted UAT with Finance users verifying dashboard outputs against TallyERP and Excel source records',
      'Managed feedback cycles, implemented refinements, and obtained formal stakeholder sign-off before deployment',
    ],
    deliverables: [
      'BRDs, functional specifications, ERDs, data dictionaries, and process workflows',
      'Dimensional data model integrating TallyERP and Excel sources',
      'ETL pipelines (SSIS) and SQL queries for automated data flow',
      'Centralised finance dashboard covering revenue, AR, dues, and settlement KPIs',
      'Multiple SSRS analytics reports for Finance, Accounts, and Senior Management',
      'UAT sign-off achieved with Finance and Senior Management stakeholders',
      'Report generation time reduced from hours to minutes',
      'Finance and Accounts teams gained real-time visibility into key financial metrics',
      'Foundation established for scalable, data-driven financial reporting across the organisation',
    ],
    takeaways: [
      'Aligning stakeholder expectations early — across Finance, Accounts, and Senior Management — ensures a clear, shared project direction',
      'Gap analysis is critical for identifying reporting inefficiencies before jumping to technical solutions',
      'Sole on-site delivery demands strong self-management, clear communication, and end-to-end ownership across both BA and BI tracks',
      'User involvement in UAT improves adoption and ensures the final solution genuinely addresses business needs',
      'Consolidating fragmented data sources into a single dimensional model is the foundation of reliable BI delivery',
    ],
    artifacts: [
      { label: 'Case Study PDF', path: '/Projects/Case%20Studies/AK_CS_03_Opine_Sarvatra.pdf' },
    ],
    comingSoon: false,
  },
  {
    slug:       'iddac',
    type:       'CASE STUDY',
    domainTag:  'GOVERNMENT · ANALYTICS',
    name:       'IDDAC — Govt. Analytics Platform',
    org:        'Savitribai Phule Pune University · Tribal Development Dept., Govt. of Maharashtra',
    year:       '2018 – 2021',
    brief:      'The Intelligent Dashboard & Data Analytics Centre (IDDAC) was a centrally-funded government analytics initiative under Article 275(1) of the Indian Constitution — mandated to unify fragmented data across 6 live welfare applications serving approximately 1 crore tribal beneficiaries across Maharashtra. I served as Sr. Project Consultant across BA, BI, and project management tracks.',
    role:       'Sr. Project Consultant at the Department of Technology, SPPU — with primary responsibility across both the BA and BI tracks, working alongside the Project Manager. Role evolved to include project management activities. Full BA+BI delivery for the Swayam & Hostel module; partial BI work across other TDD applications subject to project stage and resource availability.',
    approach: [
      'Engaged senior government stakeholders across TDD (Secretary level) and TRTI (Commissioner level), and coordinated with field offices spanning 4 Additional Tribal Commissioners and 29 Project Offices across Maharashtra',
      'Conducted stakeholder interviews, one-on-one and group meetings, and facilitated formal requirement workshops',
      'Mapped AS-IS workflows and data flows across 6 live TDD applications — identifying fragmentation points, data ownership gaps, and consolidation priorities',
      'Coordinated with multiple government IT vendors (Mahaonline, Probity Soft, NIC) to understand existing data structures and integration constraints',
      'Defined high-level functional and non-functional requirements for the analytics platform',
      'Contributed to data governance framework discussions covering data accuracy, integrity, and access controls',
      'For the Swayam & Hostel module: gathered end-to-end requirements covering hostel admissions, scholarship management, fund allocation, and student data flows',
      'Defined KPIs and reporting logic for fund allocation tracking, hostel occupancy, and student admissions data',
      'Developed dashboard specifications and data visualisation requirements for the Swayam module',
      'Navigated vendor delays through persistent follow-up, escalation, and clear requirement documentation',
      'Maintained detailed documentation across frequent government stakeholder changes to ensure continuity',
      'Managed budget reappropriation and utilization certificate submissions',
    ],
    deliverables: [
      'Full BA+BI delivery for the Swayam & Hostel module — successfully deployed for TDD staff',
      'AS-IS workflow and data flow mapping across 6 live TDD applications',
      'Requirements documentation, process maps, and data governance contributions',
      'KPI frameworks and dashboard specifications for the Swayam & Hostel module',
      'Training materials and user documentation for platform onboarding',
      'Stakeholder engagement across TDD (Secretary level), TRTI (Commissioner level), 4 ATCs, and 29 Project Offices',
      'Project governance — requirement tracking, budget reappropriation, and utilization certificate submissions',
      'Note: The broader IDDAC platform did not reach full deployment due to vendor, hardware, and stakeholder constraints. The Swayam module was the primary functional output of the engagement.',
    ],
    takeaways: [
      'Government-scale BA engagements require deep stakeholder management skills — navigating seniority, institutional complexity, and frequent personnel changes',
      'Mapping data flows across fragmented, multi-vendor government systems demands structured analytical thinking and persistent stakeholder coordination',
      'External constraints — vendor delays, trade restrictions, bureaucratic processes — are real delivery risks in large public sector initiatives. Documenting them professionally and maintaining delivery continuity is a core BA competency',
      'Delivering a working module under constraints demonstrates problem-solving and ownership beyond standard BA scope',
      'Operating across BA, BI, and PM tracks simultaneously builds a well-rounded delivery capability valuable in resource-constrained environments',
    ],
    artifacts: [
      { label: 'Case Study PDF', path: '/Projects/Case%20Studies/AK_CS_04_IDDAC.pdf' },
    ],
    comingSoon: false,
  },
  // ─── PORTFOLIO PROJECTS (comingSoon) ────────────────────────────────────────
  {
    slug:         'library-management-portal',
    type:         'PORTFOLIO PROJECT',
    domainTag:    'LIBRARY SYSTEMS',
    name:         'Library Management Portal',
    org:          'BACentric Capstone Project',
    year:         'Independent',
    brief:        '',
    role:         '',
    approach:     [],
    deliverables: [],
    takeaways:    [],
    artifacts:    [
      { label: 'Wireframes PDF', path: '/Projects/library-portal/BAC%20-%20Library%20Management%20Portal-Wireframes.pdf' },
    ],
    comingSoon:   true,
  },
  {
    slug:         'procurement-management-portal',
    type:         'PORTFOLIO PROJECT',
    domainTag:    'PROCUREMENT OPS',
    name:         'Procurement Management Portal',
    org:          'BACentric Capstone Project',
    year:         'Independent',
    brief:        '',
    role:         '',
    approach:     [],
    deliverables: [],
    takeaways:    [],
    artifacts:    [],
    comingSoon:   true,
  },
  {
    slug:         'maven-aw-dashboard',
    type:         'PORTFOLIO PROJECT',
    domainTag:    'SALES & RETAIL ANALYTICS',
    name:         'Maven AW Power BI Dashboard',
    org:          'Maven Analytics',
    year:         'Independent',
    brief:        '',
    role:         '',
    approach:     [],
    deliverables: [],
    takeaways:    [],
    artifacts:    [],
    comingSoon:   true,
  },
  {
    slug:         'finbridge-los',
    type:         'PORTFOLIO PROJECT',
    domainTag:    'BFSI · LENDING',
    name:         'FinBridge LOS',
    org:          'Independent Portfolio Project',
    year:         'In Progress',
    brief:        '',
    role:         '',
    approach:     [],
    deliverables: [],
    takeaways:    [],
    artifacts:    [],
    comingSoon:   true,
  },
]
